### PR TITLE
Fix: file handling

### LINKED ISSUE #2: Do not rely on `cp` for reflink copies
Currently metall relies on `cp --reflink=auto` to make reflink copies.
Additionally it does not sanitize the inputs to `cp` properly and pipes the output straight to stdout/stderr.

A more suitable implementation would be something like:
```c++
// includes omitted

int clone_file(std::filesystem::path const &src, std::filesystem::path const &dst) {
    int f1 = open(src.c_str(), O_RDONLY);
    if (f1 == -1) {
      perror("open src");
      return -1;
    }
    
    int f2 = open(dst.c_str(), O_WRONLY | O_CREAT | O_TRUNC);
    if (f2 == -1) {
      perror("open dst");
      close(f1);
      return -1;
    }
    
    struct stat st;
    if (fstat(f1, &st) == -1) {
      perror("stat");
      goto error;
    }
    
    if (copy_file_range(f1, NULL, f2, NULL, st.st_size, 0) == -1) {
      perror("reflink copy");
      goto error;
    }
    
    if (fchmod(f2, st.st_mode) == -1) {
      perror("chmod");
    }
    
    close(f1);
    close(f2);
    return 0;

error:
    close(f1);
    close(f2);
    return -1;
}
```

The manpage of `copy_file_range` notes that one might also call it in a loop with `seek` to skip over holes in the source file to save space in the destination.

### PR DESCRIPTION
**Pull request by liss-h**
Fixes metalls internal file handling.

### CODE REVIEW

File: test/kernel/mmap_segment_storage_test.cpp [hunk 1]
```diff
@@ -141,7 +141,7 @@ TEST(MultifileSegmentStorageTest, Openable) {
   ASSERT_TRUE(metall::mtlldetail::munmap(addr, vm_size, true));
 
   ASSERT_TRUE(segment_storage_type::openable(test_file_prefix()));
-  ASSERT_FALSE(segment_storage_type::openable(test_file_prefix() + "_dummy"));
+  ASSERT_FALSE(segment_storage_type::openable(test_file_prefix() / "dummy"));
```
Comment (bigerl) [inline test/kernel/mmap_segment_storage_test.cpp:144]: why was the `_` removed?

File: include/metall/detail/file_clone.hpp [hunk 2]
```diff
@@ -25,62 +20,68 @@ namespace metall::mtlldetail {
...
-inline bool clone_file_linux(const std::string &source_path,
-                             const std::string &destination_path) {
-  std::string command("cp --reflink=auto -R " + source_path + " " +
-                      destination_path);
-  const int status = std::system(command.c_str());
-  return (status != -1) && !!(WIFEXITED(status));
+
+inline bool clone_file_linux(int src, int dst) {
+#ifdef FICLONE
+  return ::ioctl(dst, FICLONE, src) != -1;
```
Comment (bigerl) [inline include/metall/detail/file_clone.hpp:30]: why this and not that: https://man7.org/linux/man-pages/man2/copy_file_range.2.html

File: include/metall/detail/file_clone.hpp [hunk 3]
```diff
@@ -25,62 +20,68 @@ namespace metall::mtlldetail {
...
 namespace file_clone_detail {
 #ifdef __linux__
-inline bool clone_file_linux(const std::string &source_path,
-                             const std::string &destination_path) {
-  std::string command("cp --reflink=auto -R " + source_path + " " +
-                      destination_path);
-  const int status = std::system(command.c_str());
-  return (status != -1) && !!(WIFEXITED(status));
+
+inline bool clone_file_linux(int src, int dst) {
```
Comment (bigerl) [inline include/metall/detail/file_clone.hpp:28]: why are src and dst ints? shoudn't they be 
dst: pointer to file
src: poiter to int?

Do you have a good documentation for the interface somewhere? Found only:
https://elixir.bootlin.com/linux/latest/source/fs/ioctl.c and https://docs.kernel.org/driver-api/ioctl.html# which didn't help me much.

File: include/metall/detail/file.hpp [hunk 4]
```diff
@@ -27,56 +27,29 @@
...
 inline bool os_close(const int fd) {
   if (::close(fd) == -1) {
-    METALL_ERRNO_ERROR("close");
+    METALL_ERRNO_WARN("close");
     return false;
   }
   return true;
 }
 
 inline bool os_fsync(const int fd) {
```
Comment (bigerl) [inline include/metall/detail/file.hpp:52]: add a short docstring to close and fsync

File: include/metall/detail/file_clone.hpp [hunk 5]
```diff
@@ -25,62 +20,68 @@ namespace metall::mtlldetail {
...
+inline bool clone_file_linux(const std::filesystem::path &source_path,
+                             const std::filesystem::path &destination_path) {
+  int src;
+  int dst;
+  if (!file_copy_detail::prepare_file_copy_linux(source_path, destination_path, &src, &dst)) {
+    METALL_ERROR("Unable to prepare for file copy");
+    return false;
+  }
+
+  auto close_fsync_all = [&]() {
```
Comment (bigerl) [inline include/metall/detail/file_clone.hpp]: `noexcept`

File: include/metall/detail/file.hpp [hunk 6]
```diff
@@ -338,128 +251,124 @@ inline bool free_file_space([[maybe_unused]] const int fd,
...
 
-    destination.close();
+inline bool copy_file_sparse_linux(int src, int dst) {
+  off64_t off = 0;
+  while ((off = ::lseek64(src, off, SEEK_DATA)) != -1) {
+    off64_t const hole_start = ::lseek64(src, off, SEEK_HOLE);
+    assert(hole_start != -1); // cannot fail, always an implicit hole at the end of the file
 
-    if (!metall::mtlldetail::fsync(destination_path)) {
+    if (::copy_file_range(src, &off, dst, NULL, hole_start - off, 0) == -1) {
```
Comment (bigerl) [inline include/metall/detail/file.hpp:327]: Not completely sure I got what's happening here. 

We copy things from src to dest and we are doing that between the holes. That means the resulting file will also have also so be sparse as well, right?

File: include/metall/detail/file.hpp [hunk 7]
```diff
@@ -338,128 +251,124 @@ inline bool free_file_space([[maybe_unused]] const int fd,
...
-      std::stringstream ss;
-      ss << "Something happened in the ofstream: " << destination_path;
-      METALL_ERROR(ss.str().c_str());
-      return false;
-    }
+  return true;
+}
 
-    destination.close();
+inline bool copy_file_sparse_linux(int src, int dst) {
```
Comment (bigerl) [inline include/metall/detail/file.hpp:321]: docstring. please also metion that dst is synced.

File: include/metall/detail/file.hpp [hunk 8]
```diff
@@ -519,11 +409,11 @@ inline bool get_regular_file_names(const std::string &dir_path,
 /// If <= 0 is given, the value is automatically determined.
 /// \param copy_func The actual copy function.
 /// \return  On success, returns true. On error, returns false.
+template<typename F>
 inline bool copy_files_in_directory_in_parallel_helper(
```
Comment (bigerl) [inline include/metall/detail/file.hpp:427]: If something goes wrong the output folder is a mess. To me, it would make sense to (1) report what files were successfully copied or (2) roll back all copies if one failed.

File: include/metall/detail/file.hpp [hunk 9]
```diff
@@ -27,56 +27,29 @@
...
   if (::fsync(fd) != 0) {
-    METALL_ERRNO_ERROR("fsync");
+    METALL_ERRNO_WARN("fsync");
     return false;
   }
   return true;
 }
 
-inline bool fsync(const std::string &path) {
+inline bool fsync(const std::filesystem::path &path) {
```
Comment (bigerl) [inline include/metall/detail/file.hpp:60]: When would os_close in th fsync return false?

**Review by bigerl — CHANGES_REQUESTED** [review]
Took me a while to read into what you are doing with the files. :) 
But looks good and could give us an actual boost on linux. Also, again, makes things much cleaner. 

I still have some questions here and there and some docstring request. Please have a look.

File: include/metall/detail/file_clone.hpp (hunk 3 above)
Comment (liss-h) [reply include/metall/detail/file_clone.hpp:28]: int is the standard unix file handle type see: https://www.man7.org/linux/man-pages/man2/open.2.html

File: test/kernel/mmap_segment_storage_test.cpp (hunk 1 above)
Comment (liss-h) [reply test/kernel/mmap_segment_storage_test.cpp:144]: You cannot just append to the filename with `path` so I'm creating a subdir because its less hassle

File: include/metall/detail/file_clone.hpp (hunk 2 above)
Comment (liss-h) [reply include/metall/detail/file_clone.hpp:30]: Because we definitely want a reflink copy here `copy_file_range` is technically allowed to perform a normal copy

File: include/metall/detail/file.hpp (hunk 9 above)
Comment (liss-h) [reply include/metall/detail/file.hpp:60]: if the file could not be closed. See #Errors section here: https://www.man7.org/linux/man-pages/man2/close.2.html

Comment (liss-h) [reply include/metall/detail/file.hpp:60]: In general all systemcalls can fail for various reasons

File: include/metall/detail/file.hpp (hunk 6 above)
Comment (liss-h) [reply include/metall/detail/file.hpp:327]: We are copying just the data between the holes.
Data resides always between `start = fseek(SEEK_DATA)` .. `end = fseek(SEEK_HOLE)`.
The offset into dst is set to `NULL` which means "use the internal file offset", i.e. append at the current cursor. Which will be updated after each call.

```
The following semantics apply for off_in, and similar statements
apply to off_out:

If off_in is NULL, then bytes are read from fd_in starting
from the file offset, and the file offset is adjusted by the
number of bytes copied.
```
(See #Description https://man7.org/linux/man-pages/man2/copy_file_range.2.html)

File: include/metall/detail/file_clone.hpp (hunk 3 above)
Comment (liss-h) [reply include/metall/detail/file_clone.hpp:28]: `ioctl` is a general io syscall. It acceps various inputs. The specific `ioctl` used here is that one: https://man7.org/linux/man-pages/man2/ioctl_ficlone.2.html.

```c
int ioctl(int destination_file_descriptor, FICLONE, int source_file_descriptor);
```

Comment (bigerl) [reply include/metall/detail/file_clone.hpp:28]: OK, given that things look good here. Please add the link to ioctl_ficlone.2 as a docstring and the link to open maybe to the file doc string. We'll not touch this too often I guess. So, it's good to keep the knowledge in reach.

File: include/metall/detail/file.hpp (hunk 6 above)
Comment (bigerl) [reply include/metall/detail/file.hpp:327]: ok, that's what I concluded. sounds reasonable. Leafs me know wondering how exactly sparsity is implemented on file system and kernel level. but that's definitely out of scope here.

File: include/metall/detail/file.hpp (hunk 9 above)
Comment (bigerl) [reply include/metall/detail/file.hpp:60]: And we don't track what the actual reason was. so, effectively we end up in an unrecoverable state, right?

Comment (liss-h) [reply include/metall/detail/file.hpp:60]: I would consider a file failing to close to be ignorable it only means that we use an additional file descriptor. Which is a leak, but usually unproblematic. Fsync failing is usually also not usually problematic, the data will get flushed by the kernel eventually.

Realistically, close and fsync will probably never fail if there isn't something fundamentally broken on the system.

File: include/metall/detail/file.hpp (hunk 8 above)
Comment (liss-h) [reply include/metall/detail/file.hpp:427]: The user can tell if the copy failed because the top level function returns false. 
What they do with that information is up to them I would say. Doesn't really give us any benefit to decide for them what to do.

Comment (liss-h) [reply include/metall/detail/file.hpp:427]: I think some of the usual reactions could be:
- ignore that it failed but report
- repeat however many times you want and then abort or something

Comment (bigerl) [reply include/metall/detail/file.hpp:427]: typical reason for failing would be lack of storage. Repeating would not help. I would rather abort the program or operation. But yes, that's up to the application. Here, it's mainly used for snapshots if I remember correctly. So, we probably don't need to to more here.

**Review by bigerl — APPROVED** [review]
